[package]
name = "casperlabs-client"
version = "0.1.0"
authors = ["Marc Brinkmann <marc@casperlabs.io>", "Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "A client for interacting with the CasperLabs network"

[dependencies]
base64 = "0.12.3"
casperlabs-node = { path = "../node" }
casperlabs-types = { path = "../types", features = ["std"] }
clap = "2.33.1"
futures = "0.3.5"
hex = { version = "0.4.2", features = ["serde"] }
lazy_static = "1.4.0"
rand = "0.7.3"
reqwest = "0.10.6"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync", "tcp", "time", "blocking"] }
