[package]
name = "casper-client"
version = "1.4.3" # when updating, also update 'html_root_url' in lib.rs
authors = ["Marc Brinkmann <marc@casperlabs.io>", "Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2021"
description = "A client library and binary for interacting with the Casper network"
documentation = "https://docs.rs/casper-client"
readme = "README.md"
homepage = "https://casperlabs.io"
repository = "https://github.com/casper-ecosystem/casper-client-rs"
license = "Apache-2.0"

[lib]
name = "casper_client"
path = "lib/lib.rs"

[[bin]]
name = "casper-client"
path = "src/main.rs"
doc = false

[dependencies]
async-trait = "0.1.52"
base16 = "0.2.1"
base64 = "0.13.0"
casper-execution-engine = "*"
casper-node = "*"
casper-hashing = "*"
casper-types = "*"
clap = { version = "3", features = ["cargo"] }
clap_complete = "3"
humantime = "2"
itertools = "0.10.3"
jsonrpc-lite = "0.5.0"
once_cell = "1"
rand = "0.8.5"
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "1"
tokio = { version = "1.17", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
anyhow = "1"
futures = "0.3.21"
hyper = "0.14.17"
semver = "1"
serde = "1"
tower = "0.4.12"
warp = "0.3.2"
warp-json-rpc = "0.3.0"

[patch.crates-io]
casper-execution-engine = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-node = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-hashing = { git = "https://github.com/casper-network/casper-node", branch = "dev" }
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev" }

[package.metadata.deb]
features = ["vendored-openssl"]
revision = "0"
assets = [
    ["./target/release/casper-client", "/usr/bin/casper-client", "755"],
]
extended-description = """
Package for Casper Client to connect to Casper Node.

For information on using package, see https://github.com/CasperLabs/casper-node
"""

[package.metadata.deb.variants.bionic]
name = "casper-client"
revision = "0+bionic"

[package.metadata.deb.variants.focal]
name = "casper-client"
revision = "0+focal"

[package.metadata.rpm]
package = "casper-client"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
casper-client = { path = "/usr/bin/casper-client" }
