---
name: nightly-scheduled-test

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every day at midnight
    - cron: "0 0 * * *"

jobs:
  nightly-cargo-test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        branch: [main, dev]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Slack Notification
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "*{repo}:* ${{ matrix.os }} *{branch}:* ${{ matrix.branch }}"
          message_format: "{emoji} *{workflow}:* *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
