---
name: publish-casper-client-rs

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Crate Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.crates_io_token }}
